language: node_js
node_js:
  - 8
  - 6
env:
  - FRESH_DEPS=false
  - FRESH_DEPS=true
matrix:
  exclude:
    - node_js: 6
      env: FRESH_DEPS=true
cache:
  directories:
    - $HOME/.npm
before_install:
  - npm install --global npm@^5.3.0
  - npm --version
  - if [[ ${FRESH_DEPS} == "true" ]]; then rm package-lock.json; fi
install:
  - if [[ ${FRESH_DEPS} == "true" ]]; then npm install --prefer-online; else npm install --prefer-offline; fi
  - npm install enzyme enzyme-adapter-react-16 react react-dom react-native prop-types --save
  - npm install eslint eslint-config-airbnb babel-eslint eslint-plugin-react eslint-plugin-jsx-a11y eslint-plugin-import --save-dev
after_success: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
